version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
  monitoring:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/haghob/AgriPredictSfax/src/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml