data:
  path: '/home/haghob/AgriPredictSfax/'
  raw_data_path: 'data/raw/'
  processed_data_path: 'data/processed/'

model:
  random_state: 42
  test_size: 0.2
  model_path: 'models/'
  model_name: 'model.joblib'

api:
  host: '0.0.0.0'
  port: 5000
  debug: true